// List of available object types in the system
export const objects = [
  'toponyms', // geographical entities (countries, regions, districts, localities)
  'users',    // system users
  'roles',    // user roles/permissions
  'homes',    // nursing homes or similar facilities
  'partners', // institution representatives (employees, coordinators)
  'seniors',   // residents of the nursing homes
  'volunteers', // volunteers who send cards
  'holidays',  // holidays
  'reports', // reports
  'statistics', // statistics
];

// List of operations available for each object type in the system
export const OPERATIONS = [
  // --- Toponyms ---
  {
    operation: 'ALL_OPS_TOPONYMS',
    object: 'toponyms',
    accessToAllOps: true,
    operationName: 'OPS.ALL_OPS.NAME',
    description: 'Full access to all operations with countries, regions, districts, and localities',
    objectName: 'OBJECT.TOPONYMS',
  },
  {
    operation: 'ADD_NEW_TOPONYM',
    object: 'toponyms',
    accessToAllOps: false,
    operationName: 'OPS.ADD.NAME',
    description: 'Create a new country, region, district, or locality',
    objectName: 'OBJECT.TOPONYMS',
  },
  {
    operation: 'EDIT_TOPONYM',
    object: 'toponyms',
    accessToAllOps: false,
    operationName: 'OPS.EDIT.NAME',
    description: 'Edit data of a country, region, district, or locality',
    objectName: 'OBJECT.TOPONYMS',
  },
  {
    operation: 'DELETE_TOPONYM',
    object: 'toponyms',
    accessToAllOps: false,
    operationName: 'OPS.DELETE.NAME',
    description: 'Permanently delete data of a country, region, district, or locality',
    objectName: 'OBJECT.TOPONYMS',
  },
  {
    operation: 'BLOCK_TOPONYM',
    object: 'toponyms',
    accessToAllOps: false,
    operationName: 'OPS.BLOCK.NAME',
    description: 'Block access to data of a country, region, district, or locality',
    objectName: 'OBJECT.TOPONYMS',
  },
  {
    operation: 'UNBLOCK_TOPONYM',
    object: 'toponyms',
    accessToAllOps: false,
    operationName: 'OPS.UNBLOCK.NAME',
    description: 'Unblock access to data of a country, region, district, or locality',
    objectName: 'OBJECT.TOPONYMS',
  },
  {
    operation: 'VIEW_LIMITED_TOPONYMS_LIST',
    object: 'toponyms',
    accessToAllOps: false,
    operationName: 'OPS.VIEW_LIMITED_LIST.NAME',
    description: 'View lists of countries, regions, districts, and localities with limited access',
    objectName: 'OBJECT.TOPONYMS',
    flag: 'LIMITED',
  },
  {
    operation: 'VIEW_FULL_TOPONYMS_LIST',
    object: 'toponyms',
    accessToAllOps: false,
    operationName: 'OPS.VIEW_FULL_LIST.NAME',
    description: 'View lists of countries, regions, districts, and localities with full access',
    objectName: 'OBJECT.TOPONYMS',
    flag: 'FULL',
  },

  // --- Users ---
  {
    operation: 'ALL_OPS_USERS',
    object: 'users',
    accessToAllOps: true,
    operationName: 'OPS.ALL_OPS.NAME',
    description: 'Full access to all user operations',
    objectName: 'OBJECT.USERS',
  },
  {
    operation: 'ADD_NEW_USER',
    object: 'users',
    accessToAllOps: false,
    operationName: 'OPS.ADD.NAME',
    description: 'Create a new user',
    objectName: 'OBJECT.USERS',
  },
  {
    operation: 'VIEW_USER',
    object: 'users',
    accessToAllOps: false,
    operationName: 'OPS.VIEW.NAME',
    description: 'View user profile data',
    objectName: 'OBJECT.USERS',
  },
  {
    operation: 'EDIT_USER',
    object: 'users',
    accessToAllOps: false,
    operationName: 'OPS.EDIT.NAME',
    description: 'Edit user profile data',
    objectName: 'OBJECT.USERS',
  },
    {
    operation: 'CHANGE_USER_PASSWORD',
    object: 'users',
    accessToAllOps: false,
    operationName: 'OPS.CHANGE_PASSWORD.NAME',
    description: 'Edit user password',
    objectName: 'OBJECT.USERS',
  },
  {
    operation: 'DELETE_USER',
    object: 'users',
    accessToAllOps: false,
    operationName: 'OPS.DELETE.NAME',
    description: 'Permanently delete a user profile',
    objectName: 'OBJECT.USERS',
  },
  {
    operation: 'BLOCK_USER',
    object: 'users',
    accessToAllOps: false,
    operationName: 'OPS.BLOCK.NAME',
    description: 'Block a user',
    objectName: 'OBJECT.USERS',
  },
  {
    operation: 'UNBLOCK_USER',
    object: 'users',
    accessToAllOps: false,
    operationName: 'OPS.UNBLOCK.NAME',
    description: 'Unblock a user',
    objectName: 'OBJECT.USERS',
  },
  {
    operation: 'VIEW_LIMITED_USERS_LIST',
    object: 'users',
    accessToAllOps: false,
    operationName: 'OPS.VIEW_LIMITED_LIST.NAME',
    description: 'View user list with limited access',
    objectName: 'OBJECT.USERS',
    flag: 'LIMITED',
  },
  {
    operation: 'VIEW_FULL_USERS_LIST',
    object: 'users',
    accessToAllOps: false,
    operationName: 'OPS.VIEW_FULL_LIST.NAME',
    description: 'View user list with full access',
    objectName: 'OBJECT.USERS',
    flag: 'FULL',
  },

  // --- Roles ---
  {
    operation: 'ALL_OPS_ROLES',
    object: 'roles',
    accessToAllOps: true,
    operationName: 'OPS.ALL_OPS.NAME',
    description: 'Full access to all role operations',
    objectName: 'OBJECT.ROLES',
  },
  {
    operation: 'ADD_NEW_ROLE',
    object: 'roles',
    accessToAllOps: false,
    operationName: 'OPS.ADD.NAME',
    description: 'Create a new role',
    objectName: 'OBJECT.ROLES',
  },
  {
    operation: 'EDIT_ROLE',
    object: 'roles',
    accessToAllOps: false,
    operationName: 'OPS.EDIT.NAME',
    description: 'Edit a role (update permissions)',
    objectName: 'OBJECT.ROLES',
  },
  {
    operation: 'DELETE_ROLE',
    object: 'roles',
    accessToAllOps: false,
    operationName: 'OPS.DELETE.NAME',
    description: 'Permanently delete a role',
    objectName: 'OBJECT.ROLES',
  },
  {
    operation: 'VIEW_LIMITED_ROLES_LIST',
    object: 'roles',
    accessToAllOps: false,
    operationName: 'OPS.VIEW_LIMITED_LIST.NAME',
    description: 'View role list with limited access',
    objectName: 'OBJECT.ROLES',
    flag: 'LIMITED',
  },
  {
    operation: 'VIEW_FULL_ROLES_LIST',
    object: 'roles',
    accessToAllOps: false,
    operationName: 'OPS.VIEW_FULL_LIST.NAME',
    description: 'View role list with full access',
    objectName: 'OBJECT.ROLES',
    flag: 'FULL',
  },

  // --- Homes ---
  {
    operation: 'ALL_OPS_HOMES',
    object: 'homes',
    accessToAllOps: true,
    operationName: 'OPS.ALL_OPS.NAME',
    description: 'Full access to all nursing home operations',
    objectName: 'OBJECT.HOMES',
  },
  {
    operation: 'ADD_NEW_HOME',
    object: 'homes',
    accessToAllOps: false,
    operationName: 'OPS.ADD.NAME',
    description: 'Create a new nursing home',
    objectName: 'OBJECT.HOMES',
  },
  {
    operation: 'VIEW_HOME',
    object: 'homes',
    accessToAllOps: false,
    operationName: 'OPS.VIEW.NAME',
    description: 'View nursing home profile',
    objectName: 'OBJECT.HOMES',
  },
  {
    operation: 'EDIT_HOME',
    object: 'homes',
    accessToAllOps: false,
    operationName: 'OPS.EDIT.NAME',
    description: 'Edit nursing home profile',
    objectName: 'OBJECT.HOMES',
  },
  {
    operation: 'DELETE_HOME',
    object: 'homes',
    accessToAllOps: false,
    operationName: 'OPS.DELETE.NAME',
    description: 'Permanently delete a nursing home profile',
    objectName: 'OBJECT.HOMES',
  },
  {
    operation: 'BLOCK_HOME',
    object: 'homes',
    accessToAllOps: false,
    operationName: 'OPS.BLOCK.NAME',
    description: 'Exclude nursing home from the program',
    objectName: 'OBJECT.HOMES',
  },
  {
    operation: 'UNBLOCK_HOME',
    object: 'homes',
    accessToAllOps: false,
    operationName: 'OPS.UNBLOCK.NAME',
    description: 'Reinclude nursing home in the program',
    objectName: 'OBJECT.HOMES',
  },
  {
    operation: 'VIEW_LIMITED_HOMES_LIST',
    object: 'homes',
    accessToAllOps: false,
    operationName: 'OPS.VIEW_LIMITED_LIST.NAME',
    description: 'View nursing home list with limited access',
    objectName: 'OBJECT.HOMES',
    flag: 'LIMITED',
  },
  {
    operation: 'VIEW_FULL_HOMES_LIST',
    object: 'homes',
    accessToAllOps: false,
    operationName: 'OPS.VIEW_FULL_LIST.NAME',
    description: 'View nursing home list with full access',
    objectName: 'OBJECT.HOMES',
    flag: 'FULL',
  },

  // --- Partners ---
  {
    operation: 'ALL_OPS_PARTNERS',
    object: 'partners',
    accessToAllOps: true,
    operationName: 'OPS.ALL_OPS.NAME',
    description: 'Full access to all partner operations',
    objectName: 'OBJECT.PARTNERS',
  },
  {
    operation: 'ADD_NEW_PARTNER',
    object: 'partners',
    accessToAllOps: false,
    operationName: 'OPS.ADD.NAME',
    description: 'Create a new partner',
    objectName: 'OBJECT.PARTNERS',
  },
  {
    operation: 'VIEW_PARTNER',
    object: 'partners',
    accessToAllOps: false,
    operationName: 'OPS.VIEW.NAME',
    description: 'View partner profile',
    objectName: 'OBJECT.PARTNERS',
  },
  {
    operation: 'EDIT_PARTNER',
    object: 'partners',
    accessToAllOps: false,
    operationName: 'OPS.EDIT.NAME',
    description: 'Edit partner profile',
    objectName: 'OBJECT.PARTNERS',
  },
  {
    operation: 'DELETE_PARTNER',
    object: 'partners',
    accessToAllOps: false,
    operationName: 'OPS.DELETE.NAME',
    description: 'Permanently delete a partner profile',
    objectName: 'OBJECT.PARTNERS',
  },
  {
    operation: 'BLOCK_PARTNER',
    object: 'partners',
    accessToAllOps: false,
    operationName: 'OPS.BLOCK.NAME',
    description: 'Block a partner (e.g. dismissal, termination)',
    objectName: 'OBJECT.PARTNERS',
  },
  {
    operation: 'UNBLOCK_PARTNER',
    object: 'partners',
    accessToAllOps: false,
    operationName: 'OPS.UNBLOCK.NAME',
    description: 'Unblock a partner',
    objectName: 'OBJECT.PARTNERS',
  },
  {
    operation: 'VIEW_LIMITED_PARTNERS_LIST',
    object: 'partners',
    accessToAllOps: false,
    operationName: 'OPS.VIEW_LIMITED_LIST.NAME',
    description: 'View partner list with limited access',
    objectName: 'OBJECT.PARTNERS',
    flag: 'LIMITED',
  },
  {
    operation: 'VIEW_FULL_PARTNERS_LIST',
    object: 'partners',
    accessToAllOps: false,
    operationName: 'OPS.VIEW_FULL_LIST.NAME',
    description: 'View partner list with full access',
    objectName: 'OBJECT.PARTNERS',
    flag: 'FULL',
  },

  // --- Seniors ---
  {
    operation: 'ALL_OPS_SENIORS',
    object: 'seniors',
    accessToAllOps: true,
    operationName: 'OPS.ALL_OPS.NAME',
    description: 'Full access to all resident operations',
    objectName: 'OBJECT.SENIORS',
  },
  {
    operation: 'ADD_NEW_SENIOR',
    object: 'seniors',
    accessToAllOps: false,
    operationName: 'OPS.ADD.NAME',
    description: 'Create a new resident',
    objectName: 'OBJECT.SENIORS',
  },
  {
    operation: 'VIEW_SENIOR',
    object: 'seniors',
    accessToAllOps: false,
    operationName: 'OPS.VIEW.NAME',
    description: 'View resident profile',
    objectName: 'OBJECT.SENIORS',
  },
  {
    operation: 'EDIT_SENIOR',
    object: 'seniors',
    accessToAllOps: false,
    operationName: 'OPS.EDIT.NAME',
    description: 'Edit resident profile',
    objectName: 'OBJECT.SENIORS',
  },
  {
    operation: 'DELETE_SENIOR',
    object: 'seniors',
    accessToAllOps: false,
    operationName: 'OPS.DELETE.NAME',
    description: 'Permanently delete a resident profile',
    objectName: 'OBJECT.SENIORS',
  },
  {
    operation: 'BLOCK_SENIOR',
    object: 'seniors',
    accessToAllOps: false,
    operationName: 'OPS.BLOCK.NAME',
    description: 'Block a resident (temporary absence, refusal, or other reasons)',
    objectName: 'OBJECT.SENIORS',
  },
  {
    operation: 'UNBLOCK_SENIOR',
    object: 'seniors',
    accessToAllOps: false,
    operationName: 'OPS.UNBLOCK.NAME',
    description: 'Unblock a resident',
    objectName: 'OBJECT.SENIORS',
  },
  {
    operation: 'UPDATE_LIST_OF_SENIORS',
    object: 'seniors',
    accessToAllOps: false,
    operationName: 'OPS.BULK_UPDATE.NAME',
    description: 'Bulk update resident list via XLSX upload',
    objectName: 'OBJECT.SENIORS',
  },
  {
    operation: 'VIEW_LIMITED_SENIORS_LIST',
    object: 'seniors',
    accessToAllOps: false,
    operationName: 'OPS.VIEW_LIMITED_LIST.NAME',
    description: 'View resident list with limited access',
    objectName: 'OBJECT.SENIORS',
    flag: 'LIMITED',
  },
  {
    operation: 'VIEW_FULL_SENIORS_LIST',
    object: 'seniors',
    accessToAllOps: false,
    operationName: 'OPS.VIEW_FULL_LIST.NAME',
    description: 'View resident list with full access',
    objectName: 'OBJECT.SENIORS',
    flag: 'FULL',
  },
];

