// src/app/pages/users-list/users-list.component.ts

import { Component } from '@angular/core';
import {
  userDraftSchema,
  emailControlSchema,
  facebookControlSchema,
  instagramControlSchema,
  otherContactControlSchema,
  phoneNumberControlSchema,
  telegramIdControlSchema,
  telegramNicknameControlSchema,
  vKontakteControlSchema,
  whatsAppControlSchema,
} from '@shared/schemas/user.schema';

import { TranslateModule } from '@ngx-translate/core';

import { User } from '../../interfaces/user';
import { DialogData } from '../../interfaces/dialog-props';
import {
  ColumnDefinition,
  FilterComponentSource,
  TableParams,
  ViewOption,
} from '../../interfaces/base-list';

import { zodValidator } from '../../utils/zod-validator';

import { TableComponent } from '../../shared/table/table.component';
import * as Validator from '../../utils/custom.validator';
import { Kind } from 'src/app/interfaces/advanced-model';

@Component({
  selector: 'app-users-list',
  standalone: true,
  imports: [TranslateModule, TableComponent],
  templateUrl: './users-list.component.html',
  styleUrl: './users-list.component.css',
})
export class UsersListComponent {
  kind: Kind = 'user';
  viewOptions: ViewOption[] = [
    {
      id: 'all',
      name: 'USER.VIEW_OPTIONS.ALL',
      initiallySelected: false,
    },
    {
      id: 'only-active',
      name: 'USER.VIEW_OPTIONS.ONLY_ACTIVE',
      initiallySelected: true,
    },
    {
      id: 'only-blocked',
      name: 'USER.VIEW_OPTIONS.ONLY_BLOCKED',
      initiallySelected: false,
    },
  ];

  componentType: FilterComponentSource = 'userList';

  tableParams: TableParams = {
    title: 'USER.TABLE_TITLE',
    addTitle: 'USER.ADD_USER',
    searchPlaceholder: 'USER.SEARCH_PLACEHOLDER',
    addIcon: 'person_add_alt',
  };

  IMPLICITLY_DISPLAYED_COLUMNS: ColumnDefinition[] = [
    {
      id: 1,
      columnName: 'userName',
      columnFullName: 'TABLE.COLUMNS.USER_NAME',
      isUnchangeable: true,
    },
    {
      id: 2,
      columnName: 'role',
      columnFullName: 'TABLE.COLUMNS.ROLE_NAME',
      isUnchangeable: false,
    },
    {
      id: 3,
      columnName: 'name',
      columnFullName: 'TABLE.COLUMNS.FULL_NAME',
      isUnchangeable: false,
    },
    {
      id: 4,
      columnName: 'contacts',
      columnFullName: 'TABLE.COLUMNS.CONTACTS',
      isUnchangeable: false,
    },
    {
      id: 5,
      columnName: 'address',
      columnFullName: 'TABLE.COLUMNS.ADDRESS',
      isUnchangeable: false,
    },
    {
      id: 6,
      columnName: 'dateOfStart',
      columnFullName: 'TABLE.COLUMNS.START_DATE',
      isUnchangeable: false,
    },
    {
      id: 7,
      columnName: 'comment',
      columnFullName: 'TABLE.COLUMNS.COMMENT',
      isUnchangeable: false,
    },
    {
      id: 8,
      columnName: 'isRestricted',
      columnFullName: 'TABLE.COLUMNS.STATUS',
      isUnchangeable: false,
    },
    {
      id: 9,
      columnName: 'actions',
      columnFullName: 'TABLE.COLUMNS.ACTIONS',
      isUnchangeable: false,
    },
  ];

  userDialogConfig: DialogData<User> = {
    creationTitle: 'USER.CARD.CREATION_TITLE',
    viewTitle: 'USER.CARD.VIEW_TITLE',
    controls: [
      {
        controlName: 'userName',
        value: null,
        validators: [zodValidator(userDraftSchema.shape.userName)],
        type: 'inputText',
        label: 'USER.CARD.USER_NAME_LABEL',
        placeholder: 'USER.CARD.USER_NAME_PLACEHOLDER',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'roleId',
        value: null,
        validators: [zodValidator(userDraftSchema.shape.roleId)],
        type: 'select',
        label: 'USER.CARD.ROLE_LABEL',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'password',
        value: null,
        validators: [zodValidator(userDraftSchema.shape.password)],
        type: 'inputPassword',
        label: 'USER.CARD.PASSWORD_LABEL',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'firstName',
        value: null,
        validators: [zodValidator(userDraftSchema.shape.firstName)],
        type: 'inputText',
        label: 'USER.CARD.FIRST_NAME_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'patronymic',
        value: null,
        validators: [zodValidator(userDraftSchema.shape.patronymic)],
        type: 'inputText',
        label: 'USER.CARD.PATRONYMIC_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'lastName',
        value: null,
        validators: [zodValidator(userDraftSchema.shape.lastName)],
        type: 'inputText',
        label: 'USER.CARD.LAST_NAME_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'comment',
        value: null,
        validators: [zodValidator(userDraftSchema.shape.comment)],
        type: 'inputText',
        label: 'USER.CARD.COMMENT_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'isRestricted',
        value: false,
        validators: [],
        type: 'toggle',
        label: 'USER.CARD.BLOCKED_LABEL',
        category: 'extraData',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'email',
        value: null,
        type: 'inputText',
        label: 'USER.CARD.EMAIL_LABEL',
        placeholder: 'USER.CARD.EMAIL_PLACEHOLDER',
        validators: [zodValidator(emailControlSchema)],
        errorName: 'emailFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'phoneNumber',
        value: null,
        type: 'inputText',
        label: 'USER.CARD.PHONE_NUMBER_LABEL',
        placeholder: 'USER.CARD.PHONE_NUMBER_PLACEHOLDER',
        validators: [zodValidator(phoneNumberControlSchema)],
        errorName: 'phoneNumberFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'telegramId',
        value: null,
        type: 'inputText',
        label: 'USER.CARD.TELEGRAM_ID_LABEL',
        placeholder: 'USER.CARD.TELEGRAM_ID_PLACEHOLDER',
        validators: [zodValidator(telegramIdControlSchema)],
        errorName: 'telegramIdFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'telegramPhoneNumber',
        value: null,
        type: 'inputText',
        label: 'USER.CARD.TELEGRAM_PHONE_NUMBER_LABEL',
        placeholder: 'USER.CARD.TELEGRAM_PHONE_NUMBER_PLACEHOLDER',
        validators: [zodValidator(phoneNumberControlSchema)],
        errorName: 'phoneNumberFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'telegramNickname',
        value: null,
        type: 'inputText',
        label: 'USER.CARD.TELEGRAM_NICKNAME_LABEL',
        placeholder: 'USER.CARD.TELEGRAM_NICKNAME_PLACEHOLDER',
        validators: [zodValidator(telegramNicknameControlSchema)],
        errorName: 'telegramNicknameFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'whatsApp',
        value: null,
        type: 'inputText',
        label: 'USER.CARD.WHATSAPP_LABEL',
        placeholder: 'USER.CARD.WHATSAPP_PLACEHOLDER',
        validators: [zodValidator(whatsAppControlSchema)],
        errorName: 'phoneNumberFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'vKontakte',
        value: null,
        type: 'inputText',
        label: 'USER.CARD.VKONTAKTE_LABEL',
        placeholder: 'USER.CARD.VKONTAKTE_PLACEHOLDER',
        validators: [zodValidator(vKontakteControlSchema)],
        errorName: 'vKontakteFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'instagram',
        value: null,
        type: 'inputText',
        label: 'USER.CARD.INSTAGRAM_LABEL',
        placeholder: 'USER.CARD.INSTAGRAM_PLACEHOLDER',
        validators: [zodValidator(instagramControlSchema)],
        errorName: 'instaFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'facebook',
        value: null,
        type: 'inputText',
        label: 'USER.CARD.FACEBOOK_LABEL',
        placeholder: 'USER.CARD.FACEBOOK_PLACEHOLDER',
        validators: [zodValidator(facebookControlSchema)],
        errorName: 'facebookFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'otherContact',
        value: null,
        type: 'inputText',
        label: 'USER.CARD.OTHER_CONTACT_LABEL',
        placeholder: 'USER.CARD.OTHER_CONTACT_PLACEHOLDER',
        validators: [zodValidator(otherContactControlSchema)],
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
    ],
    mainContactsValidator: [Validator.mainUserContactsValidator],
    object: null,
    componentType: 'user',
    addressFilterParams: {
      source: 'userCard',
      multiple: false,
      cols: '2',
      gutterSize: '16px',
      rowHeight: '76px',
      isShowCountry: true,
      isShowRegion: true,
      isShowDistrict: true,
      isShowLocality: true,
      class: 'none',
    },
  };

  params = {
    columns: this.IMPLICITLY_DISPLAYED_COLUMNS,
    viewOptions: this.viewOptions,
    componentType: this.componentType,
    tableParams: this.tableParams,
  };
}
