import { Component } from '@angular/core';
import {
  emailControlSchema,
  facebookControlSchema,
  instagramControlSchema,
  otherContactControlSchema,
  phoneNumberControlSchema,
  telegramIdControlSchema,
  telegramNicknameControlSchema,
  vKontakteControlSchema,
  whatsAppControlSchema,
  websiteControlSchema,
} from '../../../../shared/schemas/volunteer.schema';

import { volunteerDraftSchema } from '../../../../shared/schemas/volunteer.schema';
import { TranslateModule } from '@ngx-translate/core';
import { TableComponent } from '../../shared/table/table.component';

import { DialogData } from '../../interfaces/dialog-props';
import {
  ColumnDefinition,
  FilterComponentSource,
  TableParams,
  ViewOption,
} from '../../interfaces/base-list';

import { zodValidator } from '../../utils/zod-validator';
import * as Validator from '../../utils/custom.validator';
import { Kind, Volunteer } from '../../interfaces/advanced-model';

@Component({
  selector: 'app-volunteers-list',
  imports: [TableComponent, TranslateModule],
  templateUrl: './volunteers-list.component.html',
  styleUrl: './volunteers-list.component.css',
})
export class VolunteersListComponent {
  kind: Kind = 'volunteer';
  viewOptions: ViewOption[] = [
    {
      id: 'all',
      name: 'VOLUNTEER.VIEW_OPTIONS.ALL',
      initiallySelected: false,
    },
    {
      id: 'only-active',
      name: 'VOLUNTEER.VIEW_OPTIONS.ONLY_ACTIVE',
      initiallySelected: true,
    },
    {
      id: 'only-blocked',
      name: 'VOLUNTEER.VIEW_OPTIONS.ONLY_BLOCKED',
      initiallySelected: false,
    },
  ];

  componentType: FilterComponentSource = 'volunteerList';

  tableParams: TableParams = {
    title: 'VOLUNTEER.TABLE_TITLE',
    addTitle: 'VOLUNTEER.ADD_VOLUNTEER',
    searchPlaceholder: 'VOLUNTEER.SEARCH_PLACEHOLDER',
    addIcon: 'person_add_alt',
    labels: {
      blockLabel: 'NAV.FILTER.BLOCK_COMMENT_VOLUNTEERS',
      closeLabel: '',
      notActiveLabel: 'NAV.FILTER.NOT_ACTIVE_COMMENT_VOLUNTEERS',
    },
  };

  IMPLICITLY_DISPLAYED_COLUMNS: ColumnDefinition[] = [
    {
      id: 1,
      columnName: 'name',
      columnFullName: 'TABLE.COLUMNS.FULL_NAME',
      isUnchangeable: true,
    },
    {
      id: 2,
      columnName: 'contacts',
      columnFullName: 'TABLE.COLUMNS.CONTACTS',
      isUnchangeable: false,
    },
    {
      id: 3,
      columnName: 'address',
      columnFullName: 'TABLE.COLUMNS.ADDRESS',
      isUnchangeable: false,
    },
    {
      id: 4,
      columnName: 'institutes',
      columnFullName: 'TABLE.COLUMNS.INSTITUTES',
      isUnchangeable: false,
    },
    {
      id: 5,
      columnName: 'cooperations',
      columnFullName: 'TABLE.COLUMNS.COOPERATIONS',
      isUnchangeable: false,
    },
    {
      id: 6,
      columnName: 'dateOfStart',
      columnFullName: 'TABLE.COLUMNS.START_DATE',
      isUnchangeable: false,
    },
    {
      id: 7,
      columnName: 'comment',
      columnFullName: 'TABLE.COLUMNS.COMMENT',
      isUnchangeable: false,
    },
    {
      id: 8,
      columnName: 'isRestricted',
      columnFullName: 'TABLE.COLUMNS.STATUS',
      isUnchangeable: false,
    },
     {
      id: 9,
      columnName: 'dateOfLastOrder',
      columnFullName: 'TABLE.COLUMNS.LAST_ORDER_DATE',
      isUnchangeable: false,
    },
    {
      id: 10,
      columnName: 'actions',
      columnFullName: 'TABLE.COLUMNS.ACTIONS',
      isUnchangeable: false,
    },
  ];

  volunteerDialogConfig: DialogData<Volunteer> = {
    creationTitle: 'VOLUNTEER.CARD.CREATION_TITLE',
    viewTitle: 'VOLUNTEER.CARD.VIEW_TITLE',
    controls: [
      {
        controlName: 'firstName',
        value: null,
        validators: [zodValidator(volunteerDraftSchema.shape.firstName)],
        type: 'inputText',
        label: 'VOLUNTEER.CARD.FIRST_NAME_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'patronymic',
        value: null,
        validators: [zodValidator(volunteerDraftSchema.shape.patronymic)],
        type: 'inputText',
        label: 'VOLUNTEER.CARD.PATRONYMIC_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'lastName',
        value: null,
        validators: [zodValidator(volunteerDraftSchema.shape.lastName)],
        type: 'inputText',
        label: 'VOLUNTEER.CARD.LAST_NAME_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'comment',
        value: null,
        validators: [zodValidator(volunteerDraftSchema.shape.comment)],
        type: 'inputText',
        label: 'VOLUNTEER.CARD.COMMENT_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'subscription',
        value: false,
        validators: [],
        type: 'toggle',
        label: 'VOLUNTEER.CARD.SUBSCRIPTION_LABEL',
        category: 'subscription',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'isRestricted',
        value: false,
        validators: [],
        type: 'toggle',
        label: 'VOLUNTEER.CARD.BLOCKED_LABEL',
        category: 'extraData',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'email',
        value: null,
        type: 'inputText',
        label: 'VOLUNTEER.CARD.EMAIL_LABEL',
        placeholder: 'VOLUNTEER.CARD.EMAIL_PLACEHOLDER',
        validators: [zodValidator(emailControlSchema)],
        errorName: 'emailFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'phoneNumber',
        value: null,
        type: 'inputText',
        label: 'VOLUNTEER.CARD.PHONE_NUMBER_LABEL',
        placeholder: 'VOLUNTEER.CARD.PHONE_NUMBER_PLACEHOLDER',
        validators: [zodValidator(phoneNumberControlSchema)],
        errorName: 'phoneNumberFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'telegramId',
        value: null,
        type: 'inputText',
        label: 'VOLUNTEER.CARD.TELEGRAM_ID_LABEL',
        placeholder: 'VOLUNTEER.CARD.TELEGRAM_ID_PLACEHOLDER',
        validators: [zodValidator(telegramIdControlSchema)],
        errorName: 'telegramIdFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'telegramPhoneNumber',
        value: null,
        type: 'inputText',
        label: 'VOLUNTEER.CARD.TELEGRAM_PHONE_NUMBER_LABEL',
        placeholder: 'VOLUNTEER.CARD.TELEGRAM_PHONE_NUMBER_PLACEHOLDER',
        validators: [zodValidator(phoneNumberControlSchema)],
        errorName: 'phoneNumberFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'telegramNickname',
        value: null,
        type: 'inputText',
        label: 'VOLUNTEER.CARD.TELEGRAM_NICKNAME_LABEL',
        placeholder: 'VOLUNTEER.CARD.TELEGRAM_NICKNAME_PLACEHOLDER',
        validators: [zodValidator(telegramNicknameControlSchema)],
        errorName: 'telegramNicknameFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'whatsApp',
        value: null,
        type: 'inputText',
        label: 'VOLUNTEER.CARD.WHATSAPP_LABEL',
        placeholder: 'VOLUNTEER.CARD.WHATSAPP_PLACEHOLDER',
        validators: [zodValidator(whatsAppControlSchema)],
        errorName: 'phoneNumberFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'vKontakte',
        value: null,
        type: 'inputText',
        label: 'VOLUNTEER.CARD.VKONTAKTE_LABEL',
        placeholder: 'VOLUNTEER.CARD.VKONTAKTE_PLACEHOLDER',
        validators: [zodValidator(vKontakteControlSchema)],
        errorName: 'vKontakteFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'instagram',
        value: null,
        type: 'inputText',
        label: 'VOLUNTEER.CARD.INSTAGRAM_LABEL',
        placeholder: 'VOLUNTEER.CARD.INSTAGRAM_PLACEHOLDER',
        validators: [zodValidator(instagramControlSchema)],
        errorName: 'instaFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'facebook',
        value: null,
        type: 'inputText',
        label: 'VOLUNTEER.CARD.FACEBOOK_LABEL',
        placeholder: 'VOLUNTEER.CARD.FACEBOOK_PLACEHOLDER',
        validators: [zodValidator(facebookControlSchema)],
        errorName: 'facebookFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'website',
        value: null,
        type: 'inputText',
        label: 'PARTNER.CARD.WEBSITE_LABEL',
        placeholder: 'PARTNER.CARD.WEBSITE_PLACEHOLDER',
        validators: [zodValidator(websiteControlSchema)],
        errorName: 'websiteFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'otherContact',
        value: null,
        type: 'inputText',
        label: 'VOLUNTEER.CARD.OTHER_CONTACT_LABEL',
        placeholder: 'VOLUNTEER.CARD.OTHER_CONTACT_PLACEHOLDER',
        validators: [zodValidator(otherContactControlSchema)],
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      /*        {
        controlName: 'institutes',
        value: null,
        type: 'group',
        label: 'VOLUNTEER.CARD.INSTITUTES',
        placeholder: '',
        validators: [],
        errorName: '',
        category: 'institutes',
        formType: 'formArray',
        colspan: 6,
        rowspan: 1,
      }, */
    ],
    mainContactsValidator: [Validator.mainPartnerContactsValidator],
    object: null,
    componentType: 'volunteer',
    addressFilterParams: {
      source: 'volunteerCard',
      multiple: false,
      cols: '2',
      gutterSize: '16px',
      rowHeight: '76px',
      isShowCountry: true,
      isShowRegion: true,
      isShowDistrict: true,
      isShowLocality: true,
      class: 'none',
    },
  };

  params = {
    columns: this.IMPLICITLY_DISPLAYED_COLUMNS,
    viewOptions: this.viewOptions,
    componentType: this.componentType,
    tableParams: this.tableParams,
  };
}
