import {
  emailControlSchema,
  facebookControlSchema,
  instagramControlSchema,
  otherContactControlSchema,
  phoneNumberControlSchema,
  telegramIdControlSchema,
  telegramNicknameControlSchema,
  vKontakteControlSchema,
  volunteerDraftSchema,
  websiteControlSchema,
  whatsAppControlSchema,
} from '../../../../shared/schemas/volunteer.schema';
import { Volunteer } from '../../interfaces/advanced-model';
import { DialogData } from '../../interfaces/dialog-props';
import { zodValidator } from '../../utils/zod-validator';
import * as Validator from '../../utils/custom.validator';

export const volunteerDialogConfig: DialogData<Volunteer> = {
  creationTitle: 'VOLUNTEER.CARD.CREATION_TITLE',
  viewTitle: 'VOLUNTEER.CARD.VIEW_TITLE',
  controls: [
    {
      controlName: 'firstName',
      value: null,
      validators: [zodValidator(volunteerDraftSchema.shape.firstName)],
      type: 'inputText',
      label: 'VOLUNTEER.CARD.FIRST_NAME_LABEL',
      placeholder: '',
      category: 'mainData',
      formType: 'formControl',
      colspan: 2,
      rowspan: 1,
    },
    {
      controlName: 'patronymic',
      value: null,
      validators: [zodValidator(volunteerDraftSchema.shape.patronymic)],
      type: 'inputText',
      label: 'VOLUNTEER.CARD.PATRONYMIC_LABEL',
      placeholder: '',
      category: 'mainData',
      formType: 'formControl',
      colspan: 2,
      rowspan: 1,
    },
    {
      controlName: 'lastName',
      value: null,
      validators: [zodValidator(volunteerDraftSchema.shape.lastName)],
      type: 'inputText',
      label: 'VOLUNTEER.CARD.LAST_NAME_LABEL',
      placeholder: '',
      category: 'mainData',
      formType: 'formControl',
      colspan: 2,
      rowspan: 1,
    },
    {
      controlName: 'comment',
      value: null,
      validators: [zodValidator(volunteerDraftSchema.shape.comment)],
      type: 'inputText',
      label: 'VOLUNTEER.CARD.COMMENT_LABEL',
      placeholder: '',
      category: 'mainData',
      formType: 'formControl',
      colspan: 6,
      rowspan: 1,
    },
    {
      controlName: 'subscription',
      value: false,
      validators: [],
      type: 'toggle',
      label: 'VOLUNTEER.CARD.SUBSCRIPTION_LABEL',
      category: 'subscription',
      formType: 'formControl',
      colspan: 6,
      rowspan: 1,
    },
    {
      controlName: 'isRestricted',
      value: false,
      validators: [],
      type: 'toggle',
      label: 'VOLUNTEER.CARD.BLOCKED_LABEL',
      category: 'extraData',
      formType: 'formControl',
      colspan: 6,
      rowspan: 1,
    },
    {
      controlName: 'email',
      value: null,
      type: 'inputText',
      label: 'VOLUNTEER.CARD.EMAIL_LABEL',
      placeholder: 'VOLUNTEER.CARD.EMAIL_PLACEHOLDER',
      validators: [zodValidator(emailControlSchema)],
      errorName: 'emailFormat',
      category: 'contacts',
      formType: 'formArray',
      colspan: 3,
      rowspan: 1,
    },
    {
      controlName: 'phoneNumber',
      value: null,
      type: 'inputText',
      label: 'VOLUNTEER.CARD.PHONE_NUMBER_LABEL',
      placeholder: 'VOLUNTEER.CARD.PHONE_NUMBER_PLACEHOLDER',
      validators: [zodValidator(phoneNumberControlSchema)],
      errorName: 'phoneNumberFormat',
      category: 'contacts',
      formType: 'formArray',
      colspan: 3,
      rowspan: 1,
    },
    {
      controlName: 'telegramId',
      value: null,
      type: 'inputText',
      label: 'VOLUNTEER.CARD.TELEGRAM_ID_LABEL',
      placeholder: 'VOLUNTEER.CARD.TELEGRAM_ID_PLACEHOLDER',
      validators: [zodValidator(telegramIdControlSchema)],
      errorName: 'telegramIdFormat',
      category: 'contacts',
      formType: 'formArray',
      colspan: 3,
      rowspan: 1,
    },
    {
      controlName: 'telegramPhoneNumber',
      value: null,
      type: 'inputText',
      label: 'VOLUNTEER.CARD.TELEGRAM_PHONE_NUMBER_LABEL',
      placeholder: 'VOLUNTEER.CARD.TELEGRAM_PHONE_NUMBER_PLACEHOLDER',
      validators: [zodValidator(phoneNumberControlSchema)],
      errorName: 'phoneNumberFormat',
      category: 'contacts',
      formType: 'formArray',
      colspan: 3,
      rowspan: 1,
    },
    {
      controlName: 'telegramNickname',
      value: null,
      type: 'inputText',
      label: 'VOLUNTEER.CARD.TELEGRAM_NICKNAME_LABEL',
      placeholder: 'VOLUNTEER.CARD.TELEGRAM_NICKNAME_PLACEHOLDER',
      validators: [zodValidator(telegramNicknameControlSchema)],
      errorName: 'telegramNicknameFormat',
      category: 'contacts',
      formType: 'formArray',
      colspan: 3,
      rowspan: 1,
    },
    {
      controlName: 'whatsApp',
      value: null,
      type: 'inputText',
      label: 'VOLUNTEER.CARD.WHATSAPP_LABEL',
      placeholder: 'VOLUNTEER.CARD.WHATSAPP_PLACEHOLDER',
      validators: [zodValidator(whatsAppControlSchema)],
      errorName: 'phoneNumberFormat',
      category: 'contacts',
      formType: 'formArray',
      colspan: 3,
      rowspan: 1,
    },
    {
      controlName: 'vKontakte',
      value: null,
      type: 'inputText',
      label: 'VOLUNTEER.CARD.VKONTAKTE_LABEL',
      placeholder: 'VOLUNTEER.CARD.VKONTAKTE_PLACEHOLDER',
      validators: [zodValidator(vKontakteControlSchema)],
      errorName: 'vKontakteFormat',
      category: 'contacts',
      formType: 'formArray',
      colspan: 3,
      rowspan: 1,
    },
    {
      controlName: 'instagram',
      value: null,
      type: 'inputText',
      label: 'VOLUNTEER.CARD.INSTAGRAM_LABEL',
      placeholder: 'VOLUNTEER.CARD.INSTAGRAM_PLACEHOLDER',
      validators: [zodValidator(instagramControlSchema)],
      errorName: 'instaFormat',
      category: 'contacts',
      formType: 'formArray',
      colspan: 3,
      rowspan: 1,
    },
    {
      controlName: 'facebook',
      value: null,
      type: 'inputText',
      label: 'VOLUNTEER.CARD.FACEBOOK_LABEL',
      placeholder: 'VOLUNTEER.CARD.FACEBOOK_PLACEHOLDER',
      validators: [zodValidator(facebookControlSchema)],
      errorName: 'facebookFormat',
      category: 'contacts',
      formType: 'formArray',
      colspan: 3,
      rowspan: 1,
    },
    {
      controlName: 'website',
      value: null,
      type: 'inputText',
      label: 'PARTNER.CARD.WEBSITE_LABEL',
      placeholder: 'PARTNER.CARD.WEBSITE_PLACEHOLDER',
      validators: [zodValidator(websiteControlSchema)],
      errorName: 'websiteFormat',
      category: 'contacts',
      formType: 'formArray',
      colspan: 3,
      rowspan: 1,
    },
    {
      controlName: 'otherContact',
      value: null,
      type: 'inputText',
      label: 'VOLUNTEER.CARD.OTHER_CONTACT_LABEL',
      placeholder: 'VOLUNTEER.CARD.OTHER_CONTACT_PLACEHOLDER',
      validators: [zodValidator(otherContactControlSchema)],
      category: 'contacts',
      formType: 'formArray',
      colspan: 3,
      rowspan: 1,
    },
    /*        {
        controlName: 'institutes',
        value: null,
        type: 'group',
        label: 'VOLUNTEER.CARD.INSTITUTES',
        placeholder: '',
        validators: [],
        errorName: '',
        category: 'institutes',
        formType: 'formArray',
        colspan: 6,
        rowspan: 1,
      }, */
  ],
  mainContactsValidator: [Validator.mainPartnerContactsValidator],
  object: null,
  componentType: 'volunteer',
  addressFilterParams: {
    source: 'volunteerCard',
    multiple: false,
    cols: '2',
    gutterSize: '16px',
    rowHeight: '76px',
    isShowCountry: true,
    isShowRegion: true,
    isShowDistrict: true,
    isShowLocality: true,
    class: 'none',
  },
};
