import { Component } from '@angular/core';
import {
  emailControlSchema,
  facebookControlSchema,
  instagramControlSchema,
  otherContactControlSchema,
  phoneNumberControlSchema,
  telegramIdControlSchema,
  telegramNicknameControlSchema,
  vKontakteControlSchema,
  whatsAppControlSchema,
  websiteControlSchema,
} from '../../../../shared/schemas/home.schema';

import { homeDraftSchema } from '../../../../shared/schemas/home.schema';

import { TranslateModule } from '@ngx-translate/core';
import { DialogData } from '../../interfaces/dialog-props';
import {
  ColumnDefinition,
  FilterComponentSource,
  TableParams,
  ViewOption,
} from '../../interfaces/base-list';

import { zodValidator } from '../../utils/zod-validator';

import { TableComponent } from '../../shared/table/table.component';
import * as Validator from '../../utils/custom.validator';
import { Kind, Home } from '../../interfaces/advanced-model';

@Component({
  selector: 'app-homes-list',
  imports: [TableComponent, TranslateModule],
  templateUrl: './homes-list.component.html',
  styleUrl: './homes-list.component.css',
})
export class HomesListComponent {
  kind: Kind = 'home';
  viewOptions: ViewOption[] = [
    {
      id: 'all',
      name: 'HOME.VIEW_OPTIONS.ALL',
      initiallySelected: false,
    },
    {
      id: 'only-active',
      name: 'HOME.VIEW_OPTIONS.ONLY_ACTIVE',
      initiallySelected: true,
    },
    {
      id: 'only-blocked',
      name: 'HOME.VIEW_OPTIONS.ONLY_BLOCKED',
      initiallySelected: false,
    },
  ];

  componentType: FilterComponentSource = 'homeList';

  tableParams: TableParams = {
    title: 'HOME.TABLE_TITLE',
    addTitle: 'HOME.ADD_HOME',
    searchPlaceholder: 'HOME.SEARCH_PLACEHOLDER',
    addIcon: 'add_home',
  };

  IMPLICITLY_DISPLAYED_COLUMNS: ColumnDefinition[] = [
    {
      id: 1,
      columnName: 'regionName',
      columnFullName: 'TABLE.COLUMNS.REGION_NAME',
      isUnchangeable: true,
    },
    {
      id: 2,
      columnName: 'homeName',
      columnFullName: 'TABLE.COLUMNS.HOME_NAME',
      isUnchangeable: true,
    },
    {
      id: 3,
      columnName: 'categories', //noAddress, specialHome, acceptableForSchool
      columnFullName: 'TABLE.COLUMNS.HOME_CATEGORIES',
      isUnchangeable: false,
    },
    {
      id: 4,
      columnName: 'contacts', //officialName+contacts
      columnFullName: 'TABLE.COLUMNS.OFFICIAL_HOME_DATA',
      isUnchangeable: false,
    },
    {
      id: 5,
      columnName: 'address', //postalAddress+infoNote
      columnFullName: 'TABLE.COLUMNS.POSTAL_ADDRESS',
      isUnchangeable: false,
    },
    {
      id: 6,
      columnName: 'dateOfLastUpdate',
      columnFullName: 'TABLE.COLUMNS.LAST_UPDATE_DATE',
      isUnchangeable: false,
    },
    {
      id: 7,
      columnName: 'partners', //partner fullname+partner contacts
      columnFullName: 'TABLE.COLUMNS.PARTNERS',
      isUnchangeable: false,
    },
    {
      id: 8,
      columnName: 'dateOfStart',
      columnFullName: 'TABLE.COLUMNS.START_DATE',
      isUnchangeable: false,
    },
    {
      id: 9,
      columnName: 'comment',
      columnFullName: 'TABLE.COLUMNS.COMMENT',
      isUnchangeable: false,
    },
    {
      id: 10,
      columnName: 'isRestricted', //+status
      columnFullName: 'TABLE.COLUMNS.STATUS',
      isUnchangeable: false,
    },
    {
      id: 11,
      columnName: 'actions',
      columnFullName: 'TABLE.COLUMNS.ACTIONS',
      isUnchangeable: false,
    },
  ];

  homeDialogConfig: DialogData<Home> = {
    creationTitle: 'HOME.CARD.CREATION_TITLE',
    viewTitle: 'HOME.CARD.VIEW_TITLE',
    controls: [
      {
        controlName: 'homeName',
        value: null,
        validators: [zodValidator(homeDraftSchema.shape.homeName)],
        type: 'inputText',
        label: 'HOME.CARD.HOME_NAME_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'officialName',
        value: null,
        validators: [zodValidator(homeDraftSchema.shape.officialName)],
        type: 'inputText',
        label: 'HOME.CARD.OFFICIAL_NAME_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'noAddress',
        value: false,
        validators: [], // [zodValidator(homeDraftSchema.shape.noAddress)],
        type: 'toggle',
        label: 'HOME.CARD.NO_ADDRESS_LABEL',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'specialHome',
        value: false,
        validators: [], // [zodValidator(homeDraftSchema.shape.specialHome)],
        type: 'toggle',
        label: 'HOME.CARD.SPECIAL_HOME_LABEL',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'acceptableForSchool',
        value: false,
        validators: [], // [zodValidator(homeDraftSchema.shape.acceptableForSchool)],
        type: 'toggle',
        label: 'HOME.CARD.ACC_SCHOOL_LABEL',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'comment',
        value: null,
        validators: [zodValidator(homeDraftSchema.shape.comment)],
        type: 'inputText',
        label: 'HOME.CARD.COMMENT_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'isRestricted',
        value: false,
        validators: [],
        type: 'toggle',
        label: 'HOME.CARD.BLOCKED_LABEL',
        category: 'extraData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'isClose',
        value: false,
        validators: [],
        type: 'toggle',
        label: 'HOME.CARD.CLOSE_LABEL',
        category: 'status',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'postalAddressPart',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.POSTAL_ADDR_LABEL',
        placeholder: 'HOME.CARD.POSTAL_ADDR_PLACEHOLDER',
        validators: [zodValidator(homeDraftSchema.shape.postalAddressPart)],
        errorName: 'postalAddrFormat',
        category: 'address',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'postalName',
        value: null,
        validators: [zodValidator(homeDraftSchema.shape.postalName)],
        type: 'inputText',
        label: 'HOME.CARD.POSTAL_NAME_LABEL',
        placeholder: '',
        category: 'address',
        formType: 'formControl',
        colspan: 4,
        rowspan: 1,
      },
      {
        controlName: 'postalCode',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.POSTAL_CODE_LABEL',
        placeholder: 'HOME.CARD.POSTAL_CODE_PLACEHOLDER',
        validators: [zodValidator(homeDraftSchema.shape.postalCode)],
        errorName: 'postalCodeFormat',
        category: 'address',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },

      {
        controlName: 'infoNote',
        value: null,
        validators: [zodValidator(homeDraftSchema.shape.comment)],
        type: 'inputText',
        label: 'HOME.CARD.INFO_COMMENT_LABEL',
        placeholder: '',
        category: 'address',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'email',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.EMAIL_LABEL',
        placeholder: 'HOME.CARD.EMAIL_PLACEHOLDER',
        validators: [zodValidator(emailControlSchema)],
        errorName: 'emailFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'phoneNumber',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.PHONE_NUMBER_LABEL',
        placeholder: 'HOME.CARD.PHONE_NUMBER_PLACEHOLDER',
        validators: [zodValidator(phoneNumberControlSchema)],
        errorName: 'phoneNumberFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'telegramId',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.TELEGRAM_ID_LABEL',
        placeholder: 'HOME.CARD.TELEGRAM_ID_PLACEHOLDER',
        validators: [zodValidator(telegramIdControlSchema)],
        errorName: 'telegramIdFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'telegramPhoneNumber',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.TELEGRAM_PHONE_NUMBER_LABEL',
        placeholder: 'HOME.CARD.TELEGRAM_PHONE_NUMBER_PLACEHOLDER',
        validators: [zodValidator(phoneNumberControlSchema)],
        errorName: 'phoneNumberFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'telegramNickname',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.TELEGRAM_NICKNAME_LABEL',
        placeholder: 'HOME.CARD.TELEGRAM_NICKNAME_PLACEHOLDER',
        validators: [zodValidator(telegramNicknameControlSchema)],
        errorName: 'telegramNicknameFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'whatsApp',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.WHATSAPP_LABEL',
        placeholder: 'HOME.CARD.WHATSAPP_PLACEHOLDER',
        validators: [zodValidator(whatsAppControlSchema)],
        errorName: 'phoneNumberFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'vKontakte',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.VKONTAKTE_LABEL',
        placeholder: 'HOME.CARD.VKONTAKTE_PLACEHOLDER',
        validators: [zodValidator(vKontakteControlSchema)],
        errorName: 'vKontakteFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'instagram',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.INSTAGRAM_LABEL',
        placeholder: 'HOME.CARD.INSTAGRAM_PLACEHOLDER',
        validators: [zodValidator(instagramControlSchema)],
        errorName: 'instaFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'facebook',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.FACEBOOK_LABEL',
        placeholder: 'HOME.CARD.FACEBOOK_PLACEHOLDER',
        validators: [zodValidator(facebookControlSchema)],
        errorName: 'facebookFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'website',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.WEBSITE_LABEL',
        placeholder: 'HOME.CARD.WEBSITE_PLACEHOLDER',
        validators: [zodValidator(websiteControlSchema)],
        errorName: 'websiteFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'otherContact',
        value: null,
        type: 'inputText',
        label: 'HOME.CARD.OTHER_CONTACT_LABEL',
        placeholder: 'HOME.CARD.OTHER_CONTACT_PLACEHOLDER',
        validators: [zodValidator(otherContactControlSchema)],
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },

      //TODO: partners
    ],
    mainContactsValidator: [],
    object: null,
    componentType: 'home',
    addressFilterParams: {
      source: 'homeCard',
      multiple: false,
      cols: '2',
      gutterSize: '16px',
      rowHeight: '76px',
      isShowCountry: true,
      isShowRegion: true,
      isShowDistrict: true,
      isShowLocality: true,
      class: 'none',
    },
  };

  params = {
    columns: this.IMPLICITLY_DISPLAYED_COLUMNS,
    viewOptions: this.viewOptions,
    componentType: this.componentType,
    tableParams: this.tableParams,
  };
}
