import { Component } from '@angular/core';
import {
  emailControlSchema,
  facebookControlSchema,
  instagramControlSchema,
  otherContactControlSchema,
  phoneNumberControlSchema,
  telegramIdControlSchema,
  telegramNicknameControlSchema,
  vKontakteControlSchema,
  whatsAppControlSchema,
} from '@shared/schemas/user.schema';

import { partnerDraftSchema } from '@shared/schemas/partner.schema';

import { TranslateModule } from '@ngx-translate/core';
import { DialogData } from '../../interfaces/dialog-props';
import {
  ColumnDefinition,
  FilterComponentSource,
  TableParams,
  ViewOption,
} from '../../interfaces/base-list';

import { zodValidator } from '../../utils/zod-validator';

import { TableComponent } from '../../shared/table/table.component';
import { Partner } from '../../interfaces/partner';

@Component({
  selector: 'app-partners-list',
  imports: [TableComponent, TranslateModule],
  templateUrl: './partners-list.component.html',
  styleUrl: './partners-list.component.css',
})
export class PartnersListComponent {
  viewOptions: ViewOption[] = [
    {
      id: 'all',
      name: 'PARTNER.VIEW_OPTIONS.ALL',
      initiallySelected: false,
    },
    {
      id: 'only-active',
      name: 'PARTNER.VIEW_OPTIONS.ONLY_ACTIVE',
      initiallySelected: true,
    },
    {
      id: 'only-blocked',
      name: 'PARTNER.VIEW_OPTIONS.ONLY_BLOCKED',
      initiallySelected: false,
    },
  ];

  componentType: FilterComponentSource = 'partnerList';

  tableParams: TableParams = {
    title: 'PARTNER.TABLE_TITLE',
    addTitle: 'PARTNER.ADD_PARTNER',
    searchPlaceholder: 'PARTNER.SEARCH_PLACEHOLDER',
    addIcon: 'person_add_alt',
  };

  IMPLICITLY_DISPLAYED_COLUMNS: ColumnDefinition[] = [
    {
      id: 1,
      columnName: 'name',
      columnFullName: 'TABLE.COLUMNS.FULL_NAME',
      isUnchangeable: false,
    },
    {
      id: 2,
      columnName: 'homes',
      columnFullName: 'TABLE.COLUMNS.HOMES',
      isUnchangeable: false,
    },
    {
      id: 3,
      columnName: 'contacts',
      columnFullName: 'TABLE.COLUMNS.CONTACTS',
      isUnchangeable: false,
    },
    {
      id: 4,
      columnName: 'address',
      columnFullName: 'TABLE.COLUMNS.ADDRESS',
      isUnchangeable: false,
    },
    {
      id: 5,
      columnName: 'dateOfStart',
      columnFullName: 'TABLE.COLUMNS.START_DATE',
      isUnchangeable: false,
    },
    {
      id: 6,
      columnName: 'comment',
      columnFullName: 'TABLE.COLUMNS.COMMENT',
      isUnchangeable: false,
    },
    {
      id: 7,
      columnName: 'isRestricted',
      columnFullName: 'TABLE.COLUMNS.STATUS',
      isUnchangeable: false,
    },
    {
      id: 8,
      columnName: 'actions',
      columnFullName: 'TABLE.COLUMNS.ACTIONS',
      isUnchangeable: false,
    },
  ];

  partnerDialogConfig: DialogData<Partner> = {
    creationTitle: 'PARTNER.CARD.CREATION_TITLE',
    viewTitle: 'PARTNER.CARD.VIEW_TITLE',
    controls: [
      {
        controlName: 'firstName',
        value: null,
        validators: [zodValidator(partnerDraftSchema.shape.firstName)],
        type: 'inputText',
        label: 'PARTNER.CARD.FIRST_NAME_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'patronymic',
        value: null,
        validators: [zodValidator(partnerDraftSchema.shape.patronymic)],
        type: 'inputText',
        label: 'PARTNER.CARD.PATRONYMIC_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'lastName',
        value: null,
        validators: [zodValidator(partnerDraftSchema.shape.lastName)],
        type: 'inputText',
        label: 'PARTNER.CARD.LAST_NAME_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'comment',
        value: null,
        validators: [zodValidator(partnerDraftSchema.shape.comment)],
        type: 'inputText',
        label: 'PARTNER.CARD.COMMENT_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'isRestricted',
        value: false,
        validators: [],
        type: 'toggle',
        label: 'PARTNER.CARD.BLOCKED_LABEL',
        category: 'extraData',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'email',
        value: null,
        type: 'inputText',
        label: 'PARTNER.CARD.EMAIL_LABEL',
        placeholder: 'PARTNER.CARD.EMAIL_PLACEHOLDER',
        validators: [zodValidator(emailControlSchema)],
        errorName: 'emailFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'phoneNumber',
        value: null,
        type: 'inputText',
        label: 'PARTNER.CARD.PHONE_NUMBER_LABEL',
        placeholder: 'PARTNER.CARD.PHONE_NUMBER_PLACEHOLDER',
        validators: [zodValidator(phoneNumberControlSchema)],
        errorName: 'phoneNumberFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'telegramId',
        value: null,
        type: 'inputText',
        label: 'PARTNER.CARD.TELEGRAM_ID_LABEL',
        placeholder: 'PARTNER.CARD.TELEGRAM_ID_PLACEHOLDER',
        validators: [zodValidator(telegramIdControlSchema)],
        errorName: 'telegramIdFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'telegramPhoneNumber',
        value: null,
        type: 'inputText',
        label: 'PARTNER.CARD.TELEGRAM_PHONE_NUMBER_LABEL',
        placeholder: 'PARTNER.CARD.TELEGRAM_PHONE_NUMBER_PLACEHOLDER',
        validators: [zodValidator(phoneNumberControlSchema)],
        errorName: 'phoneNumberFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'telegramNickname',
        value: null,
        type: 'inputText',
        label: 'PARTNER.CARD.TELEGRAM_NICKNAME_LABEL',
        placeholder: 'PARTNER.CARD.TELEGRAM_NICKNAME_PLACEHOLDER',
        validators: [zodValidator(telegramNicknameControlSchema)],
        errorName: 'telegramNicknameFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'whatsApp',
        value: null,
        type: 'inputText',
        label: 'PARTNER.CARD.WHATSAPP_LABEL',
        placeholder: 'PARTNER.CARD.WHATSAPP_PLACEHOLDER',
        validators: [zodValidator(whatsAppControlSchema)],
        errorName: 'phoneNumberFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'vKontakte',
        value: null,
        type: 'inputText',
        label: 'PARTNER.CARD.VKONTAKTE_LABEL',
        placeholder: 'PARTNER.CARD.VKONTAKTE_PLACEHOLDER',
        validators: [zodValidator(vKontakteControlSchema)],
        errorName: 'vKontakteFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'instagram',
        value: null,
        type: 'inputText',
        label: 'PARTNER.CARD.INSTAGRAM_LABEL',
        placeholder: 'PARTNER.CARD.INSTAGRAM_PLACEHOLDER',
        validators: [zodValidator(instagramControlSchema)],
        errorName: 'instaFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'facebook',
        value: null,
        type: 'inputText',
        label: 'PARTNER.CARD.FACEBOOK_LABEL',
        placeholder: 'PARTNER.CARD.FACEBOOK_PLACEHOLDER',
        validators: [zodValidator(facebookControlSchema)],
        errorName: 'facebookFormat',
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'otherContact',
        value: null,
        type: 'inputText',
        label: 'PARTNER.CARD.OTHER_CONTACT_LABEL',
        placeholder: 'PARTNER.CARD.OTHER_CONTACT_PLACEHOLDER',
        validators: [zodValidator(otherContactControlSchema)],
        category: 'contacts',
        formType: 'formArray',
        colspan: 3,
        rowspan: 1,
      },
    ],

    object: null,
    componentType: 'partner',
    addressFilterParams: {
      source: 'partnerCard',
      multiple: false,
      cols: '2',
      gutterSize: '16px',
      rowHeight: '76px',
      isShowCountry: true,
      isShowRegion: true,
      isShowDistrict: true,
      isShowLocality: true,
      class: 'none',
    },
  };

  params = {
    columns: this.IMPLICITLY_DISPLAYED_COLUMNS,
    viewOptions: this.viewOptions,
    componentType: this.componentType,
    tableParams: this.tableParams,
  };
}
