import { Component } from '@angular/core';
import { seniorDraftSchema } from '../../../../shared/schemas/senior.schema';

import { TranslateModule } from '@ngx-translate/core';
import { DialogData } from '../../interfaces/dialog-props';
import {
  ColumnDefinition,
  FilterComponentSource,
  TableParams,
  ViewOption,
} from '../../interfaces/base-list';

import { zodValidator } from '../../utils/zod-validator';

import { TableComponent } from '../../shared/table/table.component';
import * as Validator from '../../utils/custom.validator';
import { Kind, Senior } from '../../interfaces/advanced-model';

@Component({
  selector: 'app-seniors-list',
  imports: [TableComponent, TranslateModule],
  templateUrl: './seniors-list.component.html',
  styleUrl: './seniors-list.component.css',
})
export class SeniorsListComponent {
  kind: Kind = 'senior';
  viewOptions: ViewOption[] = [
    {
      id: 'all',
      name: 'SENIOR.VIEW_OPTIONS.ALL',
      initiallySelected: false,
    },
    {
      id: 'only-active',
      name: 'SENIOR.VIEW_OPTIONS.ONLY_ACTIVE',
      initiallySelected: true,
    },
    {
      id: 'only-blocked',
      name: 'SENIOR.VIEW_OPTIONS.ONLY_BLOCKED',
      initiallySelected: false,
    },
  ];

  componentType: FilterComponentSource = 'seniorList';

  tableParams: TableParams = {
    title: 'SENIOR.TABLE_TITLE',
    addTitle: 'SENIOR.ADD_SENIOR',
    searchPlaceholder: 'SENIOR.SEARCH_PLACEHOLDER',
    addIcon: 'person_add_alt',
  };

  IMPLICITLY_DISPLAYED_COLUMNS: ColumnDefinition[] = [
    {
      id: 1,
      columnName: 'regionName',
      columnFullName: 'TABLE.COLUMNS.REGION_NAME',
      isUnchangeable: false,
    },
    {
      id: 2,
      columnName: 'home',
      columnFullName: 'TABLE.COLUMNS.HOME_NAME',
      isUnchangeable: false,
    },
    {
      id: 3,
      columnName: 'name',
      columnFullName: 'TABLE.COLUMNS.FULL_NAME',
      isUnchangeable: true,
    },
    {
      id: 4,
      columnName: 'gender',
      columnFullName: 'TABLE.COLUMNS.GENDER',
      isUnchangeable: true,
    },
    {
      id: 5,
      columnName: 'birthDate',
      columnFullName: 'TABLE.COLUMNS.BIRTH_DATE',
      isUnchangeable: false,
    },
    {
      id: 6,
      columnName: 'details',
      columnFullName: 'TABLE.COLUMNS.SENIOR_DETAILS',
      isUnchangeable: false,
    },
    {
      id: 7,
      columnName: 'address',
      columnFullName: 'TABLE.COLUMNS.ADDRESS',
      isUnchangeable: false,
    },
    {
      id: 8,
      columnName: 'dateOfStart',
      columnFullName: 'TABLE.COLUMNS.START_DATE',
      isUnchangeable: false,
    },
     {
      id: 9,
      columnName: 'dateOfConsent',
      columnFullName: 'TABLE.COLUMNS.CONSENT_DATE',
      isUnchangeable: false,
    },
    {
      id: 10,
      columnName: 'comment',
      columnFullName: 'TABLE.COLUMNS.COMMENT',
      isUnchangeable: false,
    },
    {
      id: 11,
      columnName: 'status',
      columnFullName: 'TABLE.COLUMNS.STATUS',
      isUnchangeable: false,
    },
    {
      id: 12,
      columnName: 'actions',
      columnFullName: 'TABLE.COLUMNS.ACTIONS',
      isUnchangeable: false,
    },
  ];

  seniorDialogConfig: DialogData<Senior> = {
    creationTitle: 'SENIOR.CARD.CREATION_TITLE',
    viewTitle: 'SENIOR.CARD.VIEW_TITLE',
    controls: [
      {
        controlName: 'firstName',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.firstName)],
        type: 'inputText',
        label: 'SENIOR.CARD.FIRST_NAME_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'confirmedFirstName',
        value: false,
        validators: [],
        type: 'checkbox',
        label: 'SENIOR.CARD.CONFIRM_FIRST_NAME_LABEL',
        category: 'mainData',
        formType: 'formControl',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'patronymic',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.patronymic)],
        type: 'inputText',
        label: 'SENIOR.CARD.PATRONYMIC_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'confirmedPatronymic',
        value: false,
        validators: [],
        type: 'checkbox',
        label: 'SENIOR.CARD.CONFIRM_PATRONYMIC_LABEL',
        category: 'mainData',
        formType: 'formControl',
        colspan: 3,
        rowspan: 1,
      },

      {
        controlName: 'lastName',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.lastName)],
        type: 'inputText',
        label: 'SENIOR.CARD.LAST_NAME_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'confirmedLastName',
        value: false,
        validators: [],
        type: 'checkbox',
        label: 'SENIOR.CARD.CONFIRM_LAST_NAME_LABEL',
        category: 'mainData',
        formType: 'formControl',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'gender',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.gender)],
        type: 'select',
        label: 'SENIOR.CARD.GENDER',
        category: 'mainData',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'birthDate',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.birthDate)],
        type: 'datePicker',
        label: 'SENIOR.CARD.BIRTH_DATE_LABEL',
        category: 'mainData',
        formType: 'formControl',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'confirmedBirthDate',
        value: false,
        validators: [],
        type: 'checkbox',
        label: 'SENIOR.CARD.CONFIRM_BIRTH_DATE_LABEL',
        category: 'mainData',
        formType: 'formControl',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'dateOfConsent',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.dateOfConsent)],
        type: 'datePicker',
        label: 'SENIOR.CARD.CONCENT_DATE_LABEL',
        category: 'mainData',
        formType: 'formControl',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'personalNoAddr',
        value: false,
        validators: [],
        type: 'checkbox',
        label: 'SENIOR.CARD.NO_ADDRESS_LABEL',
        category: 'mainData',
        formType: 'formControl',
        colspan: 3,
        rowspan: 1,
      },
      {
        controlName: 'comment',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.comment)],
        type: 'inputText',
        label: 'SENIOR.CARD.COMMENT_LABEL',
        placeholder: '',
        category: 'mainData',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'isRestricted',
        value: false,
        validators: [],
        type: 'toggle',
        label: 'SENIOR.CARD.BLOCKED_LABEL',
        category: 'extraData',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'dateOfExit',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.dateOfExit)],
        type: 'datePicker',
        label: 'SENIOR.CARD.EXIT_DATE_LABEL',
        category: 'status',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'homeId',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.homeId)],
        type: 'select',
        label: 'SENIOR.CARD.HOME_LABEL',
        category: 'address',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
      {
        controlName: 'infoNote',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.infoNote)],
        type: 'inputText',
        label: 'SENIOR.CARD.INFO_NOTE_LABEL',
        placeholder: 'SENIOR.CARD.INFO_NOTE_PLACEHOLDER',
        category: 'address',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'kindergarten',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.kindergarten)],
        type: 'inputText',
        label: 'SENIOR.CARD.KINDERGARTEN_LABEL',
        placeholder: 'SENIOR.CARD.KINDERGARTEN_PLACEHOLDER',
        category: 'details',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'teacher',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.teacher)],
        type: 'inputText',
        label: 'SENIOR.CARD.TEACHER_LABEL',
        placeholder: 'SENIOR.CARD.TEACHER_PLACEHOLDER',
        category: 'details',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'veteran',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.comment)],
        type: 'inputText',
        label: 'SENIOR.CARD.VETERAN_LABEL',
        placeholder: 'SENIOR.CARD.VETERAN_PLACEHOLDER',
        category: 'details',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'childOfWar',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.childOfWar)],
        type: 'inputText',
        label: 'SENIOR.CARD.CHILD_OF_WAR_LABEL',
        placeholder: 'SENIOR.CARD.CHILD_OF_WAR_LABEL_PLACEHOLDER',
        category: 'details',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'profession',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.profession)],
        type: 'inputText',
        label: 'SENIOR.CARD.PROFESSION_LABEL',
        placeholder: 'SENIOR.CARD.DETAILS_PLACEHOLDER',
        category: 'details',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'honoraryStatus',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.honoraryStatus)],
        type: 'inputText',
        label: 'SENIOR.CARD.HONORARY_STATUS_LABEL',
        placeholder: 'SENIOR.CARD.HONORARY_STATUS_PLACEHOLDER',
        category: 'details',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'interests',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.interests)],
        type: 'inputText',
        label: 'SENIOR.CARD.INTERESTS_LABEL',
        placeholder: 'SENIOR.CARD.INTERESTS_PLACEHOLDER',
        category: 'details',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'orthodoxBeliever',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.orthodoxBeliever)],
        type: 'inputText',
        label: 'SENIOR.CARD.ORTHODOX_BELIEVER_LABEL',
        placeholder: 'SENIOR.CARD.ORTHODOX_BELIEVER_PLACEHOLDER',
        category: 'details',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'photoLink',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.photoLink)],
        type: 'inputText',
        label: 'SENIOR.CARD.PHOTO_LINK_LABEL',
        placeholder: 'SENIOR.CARD.PHOTO_LINK_PLACEHOLDER',
        category: 'details',
        formType: 'formControl',
        colspan: 6,
        rowspan: 1,
      },
      {
        controlName: 'spouseId',
        value: null,
        validators: [zodValidator(seniorDraftSchema.shape.spouseId)],
        type: 'select',
        label: 'SENIOR.CARD.SPOUSE_LABEL',
        category: 'details',
        formType: 'formControl',
        colspan: 2,
        rowspan: 1,
      },
    ],
    mainContactsValidator: [],
    object: null,
    componentType: 'senior',
    addressFilterParams: {
      source: 'seniorCard',
      multiple: false,
      cols: '2',
      gutterSize: '16px',
      rowHeight: '76px',
      isShowCountry: true,
      isShowRegion: true,
      isShowDistrict: true,
      isShowLocality: true,
      class: 'none',
    },
  };

  params = {
    columns: this.IMPLICITLY_DISPLAYED_COLUMNS,
    viewOptions: this.viewOptions,
    componentType: this.componentType,
    tableParams: this.tableParams,
  };
}
